spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sharding_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&allowMultiQueries=true
#    username: sharding_user
#    password: sharding!@#
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/java,src/main/resources
  shardingsphere:    #https://shardingsphere.apache.org/document/5.2.0/cn/user-manual/shardingsphere-jdbc/spring-boot-starter/rules/readwrite-splitting/
    mode:
      type: Standalone
      repository:
        type: JDBC
    datasource:  #数据源配置
      names: s0,s1
      s0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/s0?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&allowMultiQueries=true
        username: sharding_user
        password: sharding!@#
      s1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/s1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&allowMultiQueries=true
        username: sharding_user
        password: sharding!@#

    rules:
      readwrite-splitting:
        data-sources:
          rw: #名字不重要
            static-strategy:
              write-data-source-name: s0
              read-data-source-names: s1
            load-balancer-name: round_robin   #负载均衡算法实现
        load-balancers:
          round_robin:   #负载均衡实现具体算法
            type: ROUND_ROBIN
    props:
      sql-show: true
      query-with-cipher-column: true
    database:
      name: logic_s
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

