server:
  port: 8080
spring:
  profiles:
    active: defshardingkey
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



